spring:
  application:
    name: Lease-microservice

server:
  port: 8086

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000